dependencies:
  - python=3.9
  - pip:
    - access
    - affine
    - anyio
    - attrs
    - bleach
    - catboost
    - certifi
    - cffi
    - click
    - click-plugins
    - Fiona
    - geographiclib
    - geopandas
    - geopy
    - geos
    - importlib-metadata
    - ipykernel
    - lightgbm
    - matplotlib
    - matplotlib-inline
    - numpy
    - pandas
    - Pillow
    - pip
    - py
    - pygeos
    - pyproj
    - pyshp
    - pytest
    - requests
    - scikit-learn
    - Scipy
    - Shapely
    - sklearn
    - spacy
    - sympy
    - thinc
    - tqdm
    - xgboost
